### PR TITLE
Upload files on clicking "Continue"

### PR DESCRIPTION
**Pull request by SuaYoo**
Refactor to upload files & generate site when user clicks "Continue" instead of on file change.

### Follow-up
Allow adding more files before "Continue" https://github.com/webrecorder/wacz-uploader/issues/14

### CODE REVIEW

**Comment by SuaYoo** [comment]
@Shrinks99 tagging you for visibility, this was feedback from @ikreymer

**Comment by RangerMauve** [comment]
TY, gonna check this out tonight. 😁

**Review by RangerMauve — APPROVED** [review]
Good idea!

**Review by ikreymer — APPROVED** [review]

**Comment by Shrinks99** [comment]
My original intention for this was to have the files upload in the background as the user adds metadata to them, that way once they're finished doing that there's no extra waiting period (or hopefully less of one) as the rest of the site is generated.  This (ideally) reduces the indeterminate waiting time?

Ultimately that's not what was previously implemented and users had to wait for file details to edit them which wasn't as good as this implementation.  I'm fine with this for an MVP if it speeds up the release.

**Pull request merged**
